### ISSUE TITLE
Some UI Components Not Working On Chrome

### ISSUE THREAD

**Issue by lamharrison** [app-generator/django-dashboard-black-pro#2]
Hi!

Just post an issue I met. After I ran runserver, I found that the UI was like this. 
![screen shot](https://user-images.githubusercontent.com/32363427/83678515-c5995980-a5d5-11ea-9299-09c7cfff479b.png)

But it works fine when I use Safari to open it.

**Comment by lamharrison** [comment]
It works now.

**Comment by app-generator** [comment]
Hello @lamharrison, 

Did you commit any change to the source code? It might help others to skip over this problem. 
Thanks.

**Comment by lamharrison** [comment]
Hi,

I just updated my Chrome version and it works perfectly, thank you!
